import { ParseOptions, TokensToRegexpOptions } from "./path-to-regex-modified.js";
export declare const DEFAULT_OPTIONS: TokensToRegexpOptions & ParseOptions;
export declare const HOSTNAME_OPTIONS: TokensToRegexpOptions & ParseOptions;
export declare const PATHNAME_OPTIONS: TokensToRegexpOptions & ParseOptions;
export declare function isAbsolutePathname(pathname: string, isPattern: boolean): boolean;
export declare function treatAsIPv6Hostname(value: string | undefined): boolean;
export declare const SPECIAL_SCHEMES: string[];
export declare function isSpecialScheme(protocol_regexp: any): boolean;
export declare function canonicalizeHash(hash: string, isPattern: boolean): string;
export declare function canonicalizeSearch(search: string, isPattern: boolean): string;
export declare function canonicalizeHostname(hostname: string, isPattern: boolean): string;
export declare function canonicalizePassword(password: string, isPattern: boolean): string;
export declare function canonicalizeUsername(username: string, isPattern: boolean): string;
export declare function canonicalizePathname(pathname: string, protocol: string | undefined, isPattern: boolean): string;
export declare function canonicalizePort(port: string, protocol: string | undefined, isPattern: boolean): string;
export declare function canonicalizeProtocol(protocol: string, isPattern: boolean): string;
export declare function defaultPortForProtocol(protocol: string | undefined): string;
export declare function protocolEncodeCallback(input: string): string;
export declare function usernameEncodeCallback(input: string): string;
export declare function passwordEncodeCallback(input: string): string;
export declare function hostnameEncodeCallback(input: string): string;
export declare function ipv6HostnameEncodeCallback(input: string): string;
export declare function portEncodeCallback(input: string): string;
export declare function standardURLPathnameEncodeCallback(input: string): string;
export declare function pathURLPathnameEncodeCallback(input: string): string;
export declare function searchEncodeCallback(input: string): string;
export declare function hashEncodeCallback(input: string): string;
